FROM ubuntu:18.04

# 中文
ENV LANG="C.UTF-8"

# 中国时区
ENV TZ=Asia/Shanghai

# 换源[阿里源]
RUN sed  -i "s/\(archive\|security\).ubuntu.com/mirrors.aliyun.com/g" /etc/apt/sources.list \
    && apt update \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && apt install -y --no-install-recommends tzdata \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
