FROM minipuppy/ubuntu18

# 源内包含版本 4.8, 5, 6, 7(默认), 8
ENV GCC_VERSION=7

RUN apt update \
    && apt install -y --no-install-recommends gcc-${GCC_VERSION} g++-${GCC_VERSION} \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
